version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/dboffice?createDatabaseIfNotExist=true
      - spring.application.name=BackendApplication
      - server.port=8080

      - spring.jpa.hibernate.ddl-auto=create
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
      - spring.datasource.username=springboot
      - spring.datasource.password=Khalid.mamdou7
      
      - spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
      - spring.jpa.generate-ddl=true
      - spring.jpa.show-sql=true
    depends_on:
      - mysqldb
    
    volumes:
      - .m2:/root/.m2
      
  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    networks:
      - springapimysql-net  
    environment:
      MYSQL_DATABASE: dboffice
      MYSQL_USER: springboot
      MYSQL_PASSWORD: Khalid.mamdou7
      MYSQL_ROOT_PASSWORD: Khalid.mamdou7
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "springboot", "-p", "Khalid.mamdou7"]
      interval: 10s  # Check every 10 seconds
      retries: 5     # Retry 5 times before considering unhealthy
networks:
  springapimysql-net: